version: '3'
services:
  frontend:
    image: authen2023/authenticket-frontend
    ports:
      - "3000:3000"

  backend:
    image: authen2023/authenticket-backend
    ports:
      - "8080:8080"

  facial:
    image: panmingwei/authenticket-facial
    ports:
      - "8000:8000"

  payment:
    image: liseon/authenticket-payment
    ports:
      - "4242:4242"