name: Authenticket Backend Workflow

on:
  push:
    branches:
      - Liseon617-patch-1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set environment variables from secrets
        run: |
          echo "$SECRETS_PROPERTIES" > .env
          echo "spring.config.import=optional:file:.env" >> .env
        env:
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}

      - name: Build Backend
        working-directory: backend
        run: mvn clean install

      - name: Junits Testing
        working-directory: backend
        run: mvn test

      - name: Build & Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: authen2023/authenticket-backend
          tags: latest
          registry: docker.io
          dockerfile: ./backend/Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
